apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie-container
          image: 525212/netflixmovie-react-app
          ports:
            - containerPort: 3000
